### ISSUE TITLE
[Improvement] Override UIKit for handling navigation

### ISSUE THREAD

**Issue by vCrespoP** [devxoul/URLNavigator#1]
Hi @devxoul,

I find your framework really interesnting, and lately, I've been playing around with Redux architecture in iOS. Summary: You keep a stack with the status, and each time something change you have a new status.
https://github.com/ReSwift/ReSwift

One thing that's still missing is handling navigation inside a state because it may be difficult to override a tabBar, or make a UINavigationViewController fire an action when dismissing the controller, etc.

This could play nicely if you knew how to do it or you may be interested in Redux.
Here is an attempt of doing that:
https://github.com/ReSwift/ReSwift-Router

Keep the good work up and thanks for making this framework available!

**Comment by devxoul** [comment]
@vCrespoP, Thanks for letting me know. Well, I'm not sure what do you want for me.
