### ISSUE TITLE
Compile error for `URLConvertible`

### ISSUE THREAD

**Issue by secretworry** [devxoul/URLNavigator#102]
![image](https://user-images.githubusercontent.com/432604/40467070-fb2f7e80-5f5a-11e8-9d4f-81efc5189b09.png)

The `String.init?(_: String)` returns an optional, it should be unwrapped before using as a subscription index.

**Comment by devxoul** [comment]
Which version of Swift and Xcode are you using?

**Comment by secretworry** [comment]
@devxoul Sorry for the late reply.
Swift 4.1, and Xcode 9.3.1.
Since the `String#subscript(_: Range<String.Index>)` returns String, why bothering wrapping it with `String.init?(_ description: String)`

**Comment by devxoul** [comment]
Hmm, this is weird. What I used is `String.init(_ substring: Substring)`. Because `component[keyRange]` returns a sequence of `Character` so I had to convert them into a `String`.

**Comment by devxoul** [comment]
@secretworry, I think you were using Swift 3 for URLNavigator. Try checking your Podfile.

**Comment by secretworry** [comment]
@devxoul my fault. thx, that solved my problem. I switched to swift 4.0 manually and didn't change the version for the pod.
