### ISSUE TITLE
http scheme is stripped in handler values

### ISSUE THREAD

**Issue by amaurydavid** [devxoul/URLNavigator#123]
Hello :)

In my app I've declared a handler matching the `myapp://browser/<string:url>` template.
When I try to open the url `myapp://browser/http://google.fr`, the url parameter given by the handler is "google.fr" and not "http://google.fr". This is an issue for me because WKWebview won't open the url "google.fr" as it's not valid.

Is there any reason for URLNavigator to strip the http scheme from a string parameter?

**Comment by devxoul** [comment]
Hi, that is obviously unintended behavior. The intended behavior is that the url should never be matched with that pattern. If I were you I would encode the url.

**Comment by amaurydavid** [comment]
Yeah that's the workaround I now use in order to have an url embedded in the deeplink. 
When I receive the deeplink I convert it in URLComponents which gives me the embedded url in the path component, and I encode that path.
Note that if I don't force the encoding of URLComponent's path, `components.url` just give me the original URL. But If I encode the path, the URLComponent encodes the path which results of an URL with a double encoded path.
So I have to manually encode the path in URLComponents, get the resulting url, feed it to URLNavigator, and call twice `removingPercentEncoding`in the handler to get back the original URL.

I'm glad I could help fixing a bug anyway, thanks for the fix :)
