### ISSUE TITLE
Needs an example project

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [devxoul/URLNavigator#16]
Hi,

Please consider adding a sample project showcasing at least the basic usage of the library. It will be really helpful.

Thanks!

**Comment by devxoul** [comment]
@Isuru-Nanayakkara, That's great idea! I think I can make an example project next week :)

**Comment by edimoldovan** [comment]
@devxoul An example project would be highly useful. I am happy to help somehow, even though I am just learning the use of this library. How can I help with putting together some examples?

**Comment by devxoul** [comment]
@Isuru-Nanayakkara @edimoldovan Thanks for waiting! #17 is an simple demo app. Feedback is always welcomed :smile:
