### ISSUE TITLE
Add Swift 3 Compatibility

### ISSUE THREAD

**Issue by rbugajewski** [devxoul/URLNavigator#21]
With the upcoming release of Swift 3 (and the newly introduced incompatibility to Swift 2.2 and older in Xcode 8) it would be great to have a separate branch with Swift 3 compatibility.

Please consider also adding a Swift 2.3 branch for people who can’t migrate to Swift 3, because of other dependencies.

**Comment by devxoul** [comment]
@rbugajewski, great idea. I made branch named `swift-3.0` and will merge into master when Swift 3 is released. Thanks for suggestion :)
