### ISSUE TITLE
Prevent push to the same ViewController

### ISSUE THREAD

**Issue by FranciscoAmado** [devxoul/URLNavigator#30]
Hi, 

First, thanks for building URLNavigator. It turns really easy to implement a deep linking strategy throughout the app.
Second, my question, is there any way to prevent opening the same view controller or the same "path" already built in into URLNavigator?

If not, I'm willing to implement some strategy, I'm just not seeing how you'll do it, right now.

Thanks once again, great job!

Francisco

**Comment by devxoul** [comment]
@FranciscoAmado, Thanks!

Actually It's not possible right now but sounds interesting. After thinking a while I came up with an option to make `URLNavigable` have its own URL as a property. But I'm not sure how could we handle if the view controller has multiple URLs. I would be really glad to see how would you implement this feature :smile:

**Comment by FranciscoAmado** [comment]
Hi @devxoul 

I'm glad our approach was close to your idea :D 
It consists on adding a required property to the `URLNavigable` protocol such as
```
   var URL: URLConvertible? { get set }
```

This allows our ViewControllers to implement this URL. Which we use to save when the`init?(url:values:)` is called and to check for a matching URL before we try to push another of the same path.
This approach allows the event to be prevented but it also implies that the "prevention" part must be handled by the application, instead of being managed by URLNavigator.
This also implies that our solution isn't appropriate for the framework but we believe it's a step towards it.

Let me know if any better idea comes up. We've fixed on our side but we'll try to think on an implementation on the URLNavigator side.

Thanks again,
Francisco

**Comment by devxoul** [comment]
@FranciscoAmado, Great. I'm gonna consider this feature by separating into two parts:

1. Extracting URLs from the `URLNavigable`
2. Making a decision in `push()`, `present()` and `open()` (e.g. `shouldPresentBlahBlah() -> Bool`)

**Comment by FranciscoAmado** [comment]
Hum I see.. 
Maybe trying to validate if the `topmost`/`from`  ViewController conforms to `URLNavigable` and its property URL matches or not the same path you're trying to `push()`/`present()` ?

**Comment by hilen** [comment]
+1. I have this problem too.  I want to call the rootViewController's function. But it present a new one and call it. It's wired. Hope you can make `URLNavigator ` have this feature.

**Comment by FranciscoAmado** [comment]
Hi, I've seen your problem and I believe it is somewhat different from mine. Still, it is an importante issue.
