### ISSUE TITLE
How to  select the UITabController's sub viewControllers?

### ISSUE THREAD

**Issue by hilen** [devxoul/URLNavigator#31]
#30 Same as this issue. And another problem is how to select the viewController that already built?

**Comment by devxoul** [comment]
You have to map `URLHandler`.

```swift
Navigator.map("myapp://tab/profile") { url, values in
  let tabBarController = findTabBarController() // need your own method
  tabBarController.selectedIndex = 1
}
```

**Comment by hilen** [comment]
Thanks for your reply, and I should put the map `URLHandler` in `func application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any) -> Bool {}` or in the `NavigationMap.initialize()`

**Comment by devxoul** [comment]
`screensort://home` and `screensort://home/share/1` is totally different. If you want to use such like `/home/share/1`, you should use URL pattern such like `screensort://home/share/<id>`.

**Comment by hilen** [comment]
Cool， many thanks

**Comment by hilen** [comment]
I had an another issue. And when the app is killed. I want to open it from `openURL`, launch the rootViewController and call its function, but it crashed. How to debug?

**Comment by devxoul** [comment]
@hilen I couldn't understand.

**Comment by hilen** [comment]
I mean I want to test the case that app is not running on the background. I open a URL like `navigator://home/share`. The normal situation is that the app is launching and call then call  the `func share()`. But now it crashed. I don't know how to debug. Cause I can't make a breakpoint.

**Comment by devxoul** [comment]
@hilen, http://stackoverflow.com/questions/18521276/ios-how-to-debug-freshly-launching-an-app-from-a-url could help you.

**Comment by hilen** [comment]
I will have a look at it. Thanks. @devxoul
