### ISSUE TITLE
Construct navigation stack

### ISSUE THREAD

**Issue by Sully73** [devxoul/URLNavigator#35]
When opening the app from a deeplink that references a viewcontroller that is 2, 3.. views deep in a UINavigationController stack, how do you build up the stack? In the included repo example if you do  a cold start from safari using `navigator://user/devxoul` url, the user can never get back to the user list.

**Comment by devxoul** [comment]
@Sully73, you should map both `URLNavigable` and `URLOpenHandler` to `navigator://user/<username>`. Use `open()` in cold-start to construct navigation stack and use `push()` or `present()` in navigating between view controllers.

```swift
Navigator.map("navigator://user/<username>", UserViewController.self)
Navigator.map("navigator://user/<username>") { url, values in
  gurad let userViewController = Navigator.viewController(for: url) as? UserViewController else {
    return false
  }
  constructNavigationStack(with: userViewController) // your custom function
}
```

**Comment by Sully73** [comment]
Great thanks!
