### ISSUE TITLE
The module import URLConvertible is not supported

### ISSUE THREAD

**Issue by meigesir** [devxoul/URLNavigator#39]
so, it collides with Alamofire, and Alamofire support Alamofire.URLConvertible, but URLNavigator not support URLNavigator.URLConvertible. It cost me much time, please help me.
![image](https://cloud.githubusercontent.com/assets/1229786/20637013/4f26e0ae-b3b4-11e6-8333-82ab8337d980.png)

**Comment by devxoul** [comment]
I named it `URLConvertible` to avoid name conflict with Alamofire but now they have `URLConvertible` 😩 #40 is the patch for this issue. You'll be able to use `URLNavigator.URLConvertible` properly after that PR has merged. Thanks for reporting :+1:

**Comment by devxoul** [comment]
@meigesir, I just released [1.1.1 version](https://github.com/devxoul/URLNavigator/releases/tag/1.1.1) :tada:
