### ISSUE TITLE
Must call designated initializer of the superclass 

### ISSUE THREAD

**Issue by Lukaz32** [devxoul/URLNavigator#4]
I've implemented the protocol `URLNavigable` in a BaseClass of mine which is inherited by all my ViewControllers. However when compiling the project it throws me the error `Must call designated initializer of the superclass BaseViewController`.
I don't really get whats the designated it wants me to implement. Do you know what I am missing?

Thanks.

**Comment by devxoul** [comment]
@Lukaz32, may I have your code?

**Comment by Lukaz32** [comment]
Sure. I've followed pretty much the way you've described in the ReadMe file.
My `BaseViewController` looks like this:

`import URLNavigator

class BaseViewController: UIViewController, URLNavigable  {
    
    convenience required init?(URL: URLConvertible, values: [String : AnyObject]) {
        // User id from URL placeholder is required!
        guard let userID = values["id"] as? Int else {
            return nil
        }
        self.init()
    }

override func viewDidLoad() {
        super.viewDidLoad()     
}
`

Then I'll have all my other controller inheriting from the `Base` one:

`class OtherViewController: BaseViewController`

**Comment by devxoul** [comment]
`OtherViewController` needs an initializer. Implement `init(nibName:bundle:)` or something else which calls `super.init(nibName: nil, bundle: nil)`.

```swift
class OtherViewController: BaseViewController {

    init(userID: Int) {
        super.init(nibName: nil, bundle: nil)
        // Initialize something else here
    }

    required convenience init?(URL: URLConvertible, values: [String : AnyObject]) {
        guard let userID = values["id"] as? Int else {
            return nil
        }
        self.init(userID: userID)
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

}
```

**Comment by Lukaz32** [comment]
Thanks a lot! I'll consider implementing it directly in the final classes.
Cheers!

**Comment by taimur** [comment]
Thanks a lot - you were that issue is solved.
