### ISSUE TITLE
Nested pushes

### ISSUE THREAD

**Issue by guisua** [devxoul/URLNavigator#44]
Hi! I was wondering if it would be able to implement nested view controller navigation. Take the example:

A chat app has: 

- Tab_Chats > Chat_List > Chat_View
- Tab_Settings > Settings_View

As of today we can have

- `"/chats"` open the list view
- `"/chat/<id>"` open a specific chat view

But would it be possible to allow for `"/chats/chat<id>"`, where both are `URLNavigable` **separately** and the combined url is interpreted **automatically**, showing the chat view animated but, afterwards, setting the list as the previous view controller in the stack. In this way we could enter the chat, but don't have it in the middle of nowhere, but in the same place as ever, where "back" takes the user back to the list view (even if it was not the prior view controller).

This would make the navigator much more useful, not having to implement each url like `"/chats/chat/<id>"` and implementing the logic by hand.

**Comment by devxoul** [comment]
@guisua, Which method(`push`, `present`, `open`) are you using to present view controllers?

**Comment by guisua** [comment]
I'm currently using both `push` and `open` (for view controllers loaded from a storyboard). Is this a functionality already that I didn't see?

**Comment by devxoul** [comment]
@guisua If you're using `open()` for presenting `Chat_View`, you can add some codes for selecting `Tab_Chats` before pushing `Chat_View`.

```swift
URLNavigator.map("/chats/chat/<id>") { url, values, userInfo in
  guard let chatID = values["id"] else { return false }
  guard let window = UIApplication.shared.delegate?.window ?? nil else { return false }
  guard let tabBarController = window.rootViewControlelr as? UITabBarController else { return false }
  tabBarController.selectedIndex = 0
  let chatViewController = ChatViewController(chatID: chatID)
  Navigator.push(chatViewController)
}
```

**Comment by guisua** [comment]
Yes, thank you. That's right, I know. However, it would be great to have the Navigator do this automatically. Please keep in mind that tab switching would be nice but not the key feature I was requesting.

My main wish would be for

```
Navigator.map("/chats", ChatsListViewController.self)
Navigator.map("/chat/<id>", ChatViewController.self)
```
to be equivalent to

```
URLNavigator.map("/chats/chat/<id>") { url, values, userInfo in
    guard let id = values["id"] as? String else { return false }
    
    if let vc = Navigator.push("/chat/\(id)") {
        // insert parent controller 
        let controllers = NSMutableArray(array: vc.navigationController.viewControllers)
        let parent = ChatsListViewController() // this is determined by the "/chats/" before the already pushed item
        controllers.insert(parent, at: controllers.count-1)
        vc.navigationController.viewControllers = Array(controllers) as! [UIViewController]
        return true
     }
     return false
}
```

and the just call `Navigator.push("/chats/chat/1234")`

Thus,
- animating the push directly into the last url item (exactly like `push` works today)
- re-building the hierarchy silently according to the url items before it

Additionally, since the maps were defined individually, both `Navigator.push("/chats")` and `Navigator.push("/chat/1234")` would work just like they do know, without the need to duplicate code implementing all the combinations as separate maps.

**Comment by guisua** [comment]
This is somewhat related to #41 but I find it a much more elegant solution due to

- calling a simple `.push("/vc1/vc2/<id>/vc3/vc4/<id>")` with no matter how many items
- not relying on each view controller to subsequently call the next push
- each vc would have to parse the `queryItems` to know what to call next, leading to a lot of lines of code, making everything much more error-prone

The delegate is a good addition (i.e. for overriding the default behaviour), but in my opinion a more elegant, url-based navigation would be a better approach. It would close the gap between normal browser or API navigation and the app navigation.

**Comment by devxoul** [comment]
@guisua,

1. URLs should be independent and should not have dependency to other resources. I don't agree with what you suggested because `/chats/chat/<id>` has dependency to `/chats` and `/chat/<id>`. This is not a good design.

2. This feature is too specific and not general enough. I don't think there are much people who need this feature. This feature requires the application's hierarchy to be designed perfectly fit to url hierarchy.

3. Browsers never work like that. Browsers will not insert a history of `/chats` page when you're about to navigate to `/chats/chat/<id>`. This method will confuse developers.

**Comment by guisua** [comment]
Well, it's your decision ultimately. However, I disagree to some extent,

1. It's not really a dependency, just an extra feature available **if** both urls have been defined. Currently, if an invalid url is passed, nothing happens as well.

2. There's no need for any hierarchy at all, that's the point. If each view controller does its own job with the passed id, for example, or any other parameters, it doesn't need to be called by a specific previous view controller (as seems to be the way the #41 implementation is going, where each view controller would the call another push, etc.).

3. Poor choice of words here, sorry. I meant more like the concept of how websites or APIs are built, where you first access a list of some elements, then one in particular, etc. I was not necessarily referring to the navigation per se (as in forward/backward).

Anyhow, feel free to close the issue if you don't deem it useful or likely to be implemented.

**Comment by francksyren** [comment]
I agree with @guisua 
This feature would be very helpful.
I was looking at this library because I hoped that maybe it could have helped me to handle Push Notifications. I would like to have Router that keeps a certain hierarchy. Consider that your application is running and your current state is /chats/chat/12345/editParticipants where editParticipants would be a *modal* controller in a Navigation Controller that you open from a detail chat screen). Then you receive a notification for the chat with ID = 54321, if the user taps on it, I want to be back to /chats/chat/54321, I don't want to push/present that chat view from where the app currently is.

**Comment by devxoul** [comment]
@francksyren, thanks for detailed explanation. However URLNavigator has no plan for support hierarchy at this time. You may use `open()` for navigating to a view controller with keeping a hierarchy manually.
