### ISSUE TITLE
Support universal links

### ISSUE THREAD

**Issue by sunflash** [devxoul/URLNavigator#5]
https://www.example.com/profile?username=foo
It's seem not possible to extract query parameter from web link, in this case "username"

**Comment by devxoul** [comment]
@sunflash, how did you map the url?

**Comment by sunflash** [comment]
I end up to using  kylef/URITemplate.swift with some custom mapping code to make my own router.

**Comment by devxoul** [comment]
Cool.

**Comment by sunflash** [comment]
http://blog.hokolinks.com/how-to-implement-apple-universal-links-on-ios-9/
https://github.com/kylef/URITemplate.swift
https://tools.ietf.org/html/rfc6570

**Comment by devxoul** [comment]
So, what was the problem that username cannot be extracted?

Well, I think this could work:

```swift
Navigator.map("https://www.example.com/profile", ProfileViewController.self)
```

```swift
final class ProfileViewController: UIViewController, URLNavigable {

    // ...

    convenience init?(URL: URLConvertible, values: [String: AnyObject]) {
        let parameters = // extract parameters from URL.URLValue.queryString
        guard let username = parameters["username"] as? String else {
            return nil
        }
        self.init(username: username)
    }

    // ...
}
```

**Comment by sunflash** [comment]
Hi, thanks for your answer. I was use follow example, but URL don't have parameters as property
`        Navigator.map("myapp://alert") { URL, values in
            print(URL.parameters["title"])
            print(URL.parameters["message"])
            self.someUtilityMethod()
            return true
        }
`
If I try like https://www.example.com/message?title=Hello&message=World, then I could get query string from url or decompose query items by using NSURLComponent, "URL.parameters" magic don't seem to work.

`        Navigator.map("https://www.example.com/message") { url, values in
            let query = url.URLValue?.query   //Optional("title=Hello&message=World") 
            return true
        }
`

**Comment by devxoul** [comment]
@sunflash, Oh sorry. I forgot that I didn't make `parameters` utility property at `URLConvertible`. I'll make it available as soon as possible.
