### ISSUE TITLE
Protocol Conform issue

### ISSUE THREAD

**Issue by taimur** [devxoul/URLNavigator#51]
When I implemented protocol in my ViewController I got this error. can someone please assist. I have checked the demo projects and the initializers are mentioned directly inside the class.

- 'required' initializer must be declared directly in class 'MotorViewController' (not in an extension)

- 'Initializer requirement 'init(navigation:)' can only be satisfied by a `required` initializer in the definition of non-final class 'MotorViewController'

http://imgur.com/4u51uuw

**Comment by devxoul** [comment]
I think this is possibly duplicated with #4. If you don't think so, could you please share your code? Thanks!

**Comment by taimur** [comment]
@devxoul Thanks a lot - you were that issue is solved.
Can you please guide me on this one too.

In the NavigationMap when I map my view controllers - I receive this error

`Navigator.map("navigator://motors/<vehicleName>", MotorViewController.self)` 

Cannot convert value of type 'MotorViewController.Type' to expected argument type 'URLNavigator.URLOpenHandler' (aka '(URLConvertible, Dictionary<String, Any>) -> Bool')

**Comment by devxoul** [comment]
@taimur glad to hear that! Does `MotorViewController` conform to protocol `URLNaviable`?

**Comment by taimur** [comment]
Yeah `MotorViewController` conforms to `URLNavigable`.
Thats the code of the whole class

```
import UIKit
import URLNavigator

class MotorViewController: UIViewController {

  let vehiclename: String
    override func viewDidLoad() {
        super.viewDidLoad()

        // Do any additional setup after loading the view.
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
  
  init(vehiclename: String) {
    self.vehiclename = vehiclename
    super.init(nibName: nil, bundle: nil)
    self.title = "\(vehiclename)"
  }
  
  required init?(coder aDecoder: NSCoder) {
    fatalError("init(coder:) has not been implemented")
  }
  
  
  required convenience init?(URL: URLConvertible, values: [String : AnyObject]) {
    guard let vehicle = values["vehicle"] as? String else {
      return nil
    }
    self.init(vehiclename: vehicle)
  }
  
  
}


```

**Comment by devxoul** [comment]
Could you try with the code below?

```diff
- class MotorViewController: UIViewController {
+ class MotorViewController: UIViewController, URLNavigable {
```

**Comment by taimur** [comment]
Thank you so much - Highly appreciate your efforts. You are genius
