### ISSUE TITLE
Navigation push function returns nil

### ISSUE THREAD

**Issue by taimur** [devxoul/URLNavigator#53]
Whenever I push a VC through _push_ method of _Navigator_ it goes to nil statement at the guard

Here is how I am doing it. I have NavigationMap file with these lines

```
static func initialize() {
let URL = "navigator://propertyDPV"
Navigator.present(URL)
}
```

In URLNavigator.swift class the function return nil
```
@discardableResult
  open func push(
    _ url: URLConvertible,
    context: NavigationContext? = nil,
    from: UINavigationController? = nil,
    animated: Bool = true
  ) -> UIViewController? {
    guard let viewController = self.viewController(for: url, context: context) else {
      return nil
    }
    return self.push(viewController, from: from, animated: animated)
  }
```

**Comment by devxoul** [comment]
Did you map the url before pushing or presenting?

**Comment by taimur** [comment]
I mapped it but I couldn't call it in the objectiveC version of my AppDelegate. I had to call it in the MainVC which is written in swift and it worked. Thanks a lot 👍
