### ISSUE TITLE
Using URLNavigator with ObjC files

### ISSUE THREAD

**Issue by taimur** [devxoul/URLNavigator#54]
Can anyone please confirm if we can use the library with files / classes written in ObjectiveC. I have used the URLNavigator library and it works perfect with Swift files but I couldn't make it work with ObjectiveC files. if convenient can anyone mention the code ( a screenshot would work ) of the class  in which protocol of URLNavigator is implemented and the VC is pushed or presented using URLNavigator. Thanks a lot !

**Comment by devxoul** [comment]
You may make the extension of objective-C view controller to conform URLNavigable.

```objc
@interface MyViewController : UIViewController
+ (instancetype)initWithFoo:(Foo *);
@end
```

```swift
extension MyViewController: URLNavigable {
  convenience init?(navigation: Navigation) {
    self.init(foo: ...)
  }
}
```

**Comment by klaudynamarciniak** [comment]
@devxoul does it work for you? I am getting this error: "Initializer requirement 'init(navigation:)' can only be satisfied by a `required` initializer in the definition of non-final class 'BJShopVC' . It is impossible to use required keyword in the extension or make objc class final. I don't see any workaround for this one. :(
