### ISSUE TITLE
Dependency Injection

### ISSUE THREAD

**Issue by zdenektopic** [devxoul/URLNavigator#55]
I think it should be possible to map URL to some closure that returns UIViewController instead of just Navigatable.

I am using Swinject in project and I am unable to use URLNavigator DI container as it requires type only and I cannot return an instance in any way.

Simple example:
```swift
Navigator.map("//list/<approvalRequestType>") { navigation in 
  return ListViewController(foo: navigation.values["approvalRequestType"] as! Int) 
}
```

**Comment by devxoul** [comment]
Why not just make `ListViewController` conform to protocol `URLNavigable` and return it?

```swift
extension ListViewController: URLNavigable {
}

Navigator.map("//list/<approvalRequestType>", ListViewController.self)
```

**Comment by zdenektopic** [comment]
No. What i need is approx this:
```swift
let container = Container.default
Navigator.map("//list/<approvalRequestType>") { navigation in 
  return container.resolve(ListViewController.self)
}
```
Possibly pass arguments to resolve but I am on phone now.

**Comment by zdenektopic** [comment]
@devxoul checkout [Swinject](https://github.com/Swinject/Swinject) project.

**Comment by zdenektopic** [comment]
I can see there are other 2 PRs with something similar, so I guess this is wanted feature :)

**Comment by devxoul** [comment]
This is implemented in [URLNavigator 2](https://github.com/devxoul/URLNavigator/releases/tag/2.0.0). Thanks!
