### ISSUE TITLE
Block or Delegate

### ISSUE THREAD

**Issue by yusoul** [devxoul/URLNavigator#60]
I would like to know, how to deal with  parameter  callback?

**Comment by devxoul** [comment]
You can pass `Any` value to `push()` and `present()`:

```swift
Navigator.push("myapp://foo", context: myCallbackClosure)
Navigator.present("myapp://foo", context: myCallbackClosure)
```

**Comment by yusoul** [comment]
Use the storyboard, how to handle the block？
![image](https://user-images.githubusercontent.com/19601094/28048246-3d4489a6-6622-11e7-9dfc-ba49fc5c8d44.png)
![image](https://user-images.githubusercontent.com/19601094/28048264-5b52da2e-6622-11e7-95e5-6db82d7b943a.png)

**Comment by devxoul** [comment]
That's not supported with `open()`. I'll keep this in my mind for URLNavigator 2.

**Comment by yusoul** [comment]
When will the  URLNavigator 2  be released?

**Comment by devxoul** [comment]
There's no exact plan. I'll start working when I'm available :-)

**Comment by yusoul** [comment]
Thank you for your contribution!!!

**Comment by devxoul** [comment]
This is implemented in [URLNavigator 2](https://github.com/devxoul/URLNavigator/releases/tag/2.0.0). Thanks!
