### ISSUE TITLE
Present with custom navigation controller

### ISSUE THREAD

**Issue by kgonyon** [devxoul/URLNavigator#61]
First off thank you for making such a useful library. It has saved me and my team a lot of time.

Our application uses a custom subclass of UINavigationController. I wanted to see if there are any plans to be able to specify the navigation controller to use for wrapping when calling present. 

Our current work around is to use open similar to the storyboard work around, however we lose the ability to use the Navigable protocol.

**Comment by devxoul** [comment]
At this time custom navigation controller class is not yet supported. In this case I used to create a custom navigation controller with a specific root view controller instead. I'll make sure that this will be resolved in URLNavigator 2.
