### ISSUE TITLE
Swift 4 conversion

### ISSUE THREAD

**Issue by Gerrel** [devxoul/URLNavigator#62]

**Comment by HaiTeng-Wang** [comment]
what? A man, a plan a canal:panama.

**Comment by devxoul** [comment]
I'm currently working on URLNavigator 2 and it'll be written in Swift 4.

**Comment by devxoul** [comment]
[URLNavigator 2](https://github.com/devxoul/URLNavigator/releases/tag/2.0.0) is out. It fully supports Swift 4 :tada:
