### ISSUE TITLE
Global fallback router

### ISSUE THREAD

**Issue by iShawnWang** [devxoul/URLNavigator#64]
- I want a fallback router such as 'shceme://*', and when all the others can't match, this handler be called
- so that i can present a viewcontroller to show something like `Comming Soon ~` and do analytics, any build in support for this ?

# :D

**Comment by devxoul** [comment]
Could you test with the code below? I think this might work but not 100% sure.

```swift
Navigator.map("myapp://vc1", ViewController1.self)
Navigator.map("myapp://vc2", ViewController2.self)
Navigator.map("myapp://<path:_>", ComingSoonViewController.self)
```

**Comment by iShawnWang** [comment]
It works like a charm, and i make a PR #65
