### ISSUE TITLE
tvOS support

### ISSUE THREAD

**Issue by bill350** [devxoul/URLNavigator#66]
Hi @devxoul 

What about a tvOS support ?

I think it is easy because of the same architecture on tvOS about windows & co. We use UIKit and Foundation and non-specific iOS APIs.

Are you agree ?
I think add a demo project for tvOS and change the podspec and it will be ok :)

**Comment by devxoul** [comment]
@bill350 Sounds great! I will check this in a next few days :)

**Comment by bill350** [comment]
@devxoul see https://github.com/devxoul/URLNavigator/pull/67 ;)
