### ISSUE TITLE
 instantiate viewcontroller from storyboard rather than init?

### ISSUE THREAD

**Issue by wppd** [devxoul/URLNavigator#7]
I'm pretty new to swift and ios development. 

here is my scenario:

in the Home controller, user clicks a post and goes to Post controller.

`Navigator.pushURL(postUrl)` is triggerd in Home Controller.

I have a connected outlet `UIWebView` in Post view controller.

the outlet is `nil` according to xcode debug console once pushed to Post controller.

from SO http://stackoverflow.com/questions/25379616/uiviewcontroller-alloc-and-init-vs-instantiate 

it should instantiate the Post controller from storyboard so that the outlet will be configured automatically.

Is there any workaround to achieve this?

**Comment by devxoul** [comment]
@wppd, It's not available at this time. You should initialize your view controller programmatically.

However, you can map the closure to instantiate and push view controller from Storyboard.

```swift
self.navigator.map("https://<path:_>") { _ in
    let postViewController = UIStoryboard(name: "Main", bundle: nil).instantiateInitialViewController()
    topMostViewController.navigationController?.pushViewController(postViewController, animated: true)
}
```

**Comment by wppd** [comment]
@devxoul thanks for your reply. I think this would be a workaround.

**Comment by SeongBrave** [comment]
in  storyboard can  use Navigator.pushURL() or Navigator.presentURL()  ？because i am not sure  use which one

**Comment by devxoul** [comment]
@SeongBrave, I'm not sure what did you mean :)

**Comment by SeongBrave** [comment]
@devxoul   when I use  'Navigator.map("myapp://user/<int:id>", UserViewController.self)' type, I can Navigator.push("myapp://user/123") or Navigator.present("myapp://user/123")

 but when I use storyboard , I set  `self.navigator.map("myapp://post/<int:id>") { URL, values in
    guard let postID = values["id"] as? Int else {
        return false
    }
    let postViewController = UIStoryboard(name: "Main", bundle: nil).instantiateInitialViewController()
    Navigator.push(postViewController)
    return true
}`
I only use  `Navigator.openURL("myapp://post/12345")`  this mean  `Navigator.push(postViewController)` but not can `Navigator.present(postViewController)`
I am sorry for My poor English level

**Comment by devxoul** [comment]
@SeongBrave, yeah, that is the limitation of current version :(
