### ISSUE TITLE
Request: Check if route is valid/mapped

### ISSUE THREAD

**Issue by BabyAzerty** [devxoul/URLNavigator#70]
It would be nice to test a route "foo://bar" so we know it is has been mapped:

Maybe?

```swift
// In URLNavigator.swift
// Return true if route is found
open func map(_ urlPattern: URLConvertible) -> Bool {
    let URLString = URLMatcher.default.normalized(urlPattern, scheme: self.scheme).urlStringValue
    return self.urlMap[URLString] != nil ? true : (self.urlOpenHandlers[URLString] != nil ? true : false)
}
```

**Comment by devxoul** [comment]
You may want to use:

```swift
let isMapped = Navigator.viewController(for: "foo://bar") != nil
```

**Comment by BabyAzerty** [comment]
I wouldn't recommend this method to check if a route is mapped for 3 reasons:
- It relies on a failable init which can return nil even though the map did exist. 
- It does init a controller which can create a lot of overhead if the controller is big and has a plethora of variables. 
- It doesn't check against openURLHandlers.

**Comment by devxoul** [comment]
When do you need this feature?

**Comment by BabyAzerty** [comment]
Ideally with URLNavigator 2 which I hope is for this year :)
Let me know if you want me to make a PR with the Unit Tests.

**Comment by devxoul** [comment]
Oh, I mean 'why do you need?'

**Comment by BabyAzerty** [comment]
Example:
- Unit Testing my app. I try a list of static strings, I want to know if it will be caught by my app. Some routes, when being triggered, will do some contextual processing which will always fail in Unit Tests even though the routes do exist. 

If you have other ways, let me know.

**Comment by devxoul** [comment]
Oh I see. Actually current version of URLNavigator is not really test-friendly. It would be great if it can be included in URLNavigator 2.

**Comment by BabyAzerty** [comment]
I would gladly contribute to URLNavigator2 to include Unit Tests

**Comment by devxoul** [comment]
This is implemented in [URLNavigator 2](https://github.com/devxoul/URLNavigator/releases/tag/2.0.0). You may use view controller factory to achieve this. Thanks!
