### ISSUE TITLE
Request: Remove a route from the map

### ISSUE THREAD

**Issue by BabyAzerty** [devxoul/URLNavigator#71]
It would be nice to remove a route handler from the map :)

Maybe?

```swift
// In URLNavigator.swift
open func remove(_ urlPattern: URLConvertible) {
    let URLString = URLMatcher.default.normalized(urlPattern, scheme: self.scheme).urlStringValue
    if self.urlMap.removeValue(forKey: URLString) == nil {
        self.urlOpenHandlers.removeValue(forKey: URLString)
    }
}

open func removeAllURLPatterns() {
    self.urlMap.removeAll()
    self.urlOpenHandlers.removeAll()
}
```

**Comment by devxoul** [comment]
It makes sense. I'll add this issue to URLNavigator 2 milestone :)

**Comment by devxoul** [comment]
I'm curious which situation do you need this feature.

**Comment by BabyAzerty** [comment]
Example:
- I handle a user on my app. He can be a normal user or a VIP or a VVIP or any other level of access. 
Depending on who he is, he has access to more features (and more routes opening). 
And a user can be downgraded or upgraded in real time. 
When he is downgraded, I need to remove routes, when upgraded, I need to add routes.

**Comment by devxoul** [comment]
Hmm, I think the route mappings should be static. How about returning an instance of a view controller if the user has a permission and `nil` if the user has no permission?

**Comment by BabyAzerty** [comment]
Controllers should be independent (at least in my paradigm) for re-usability reasons.

The logic to know if a controller can be opened/created is either:
- set in the init but it makes the controller aware of the app state, for example the inside the init, there will be a DB fetch to check if the current user has this or that right.
- set in a manager that handles controllers' initialisation.

Our current app architecture doesn't allow us to use the first option, so there is only the second option left.
And with the second option, I only see 2 possible ways to execute it:
- I transform most `Navigator.open("/route", FooController.self)` into
```swift
Navigator.open("/route") {
    //Logic to see if this route can be opened or not
}
```
but this approach is less maintainable and clear.
- Or the manager adds/removes dynamically the map from URLNavigator (as soon as a user is downgraded/upgraded in the case of my example).

**Comment by devxoul** [comment]
How about [this approach](https://github.com/devxoul/URLNavigator/issues/30)? I'm planning to implement a way to allow or block push/present view controller. It can be a delegate or something else. For example of delegate:

```swift
func shouldPresentURL(_ url: URL, otherUsefulInformations: Foo) -> Bool {
  return User.current.isVIP
}
```

**Comment by BabyAzerty** [comment]
It looks great!

**Comment by devxoul** [comment]
This is implemented in [URLNavigator 2](https://github.com/devxoul/URLNavigator/releases/tag/2.0.0). Thanks!
