### ISSUE TITLE
Carthage cannot build v1.2.5 with no-use-binaries option

### ISSUE THREAD

**Issue by YukiOya** [devxoul/URLNavigator#74]
`carthage bootstrap --no-use-binaries` do nothing  because `URLNavigator.xcodeproj` is removed on [this commit](https://github.com/devxoul/URLNavigator/commit/7e81c9136181ff09167e4375946d0616e7255eea).

Could you restore `URLNavigator.xcodeproj` directory or share the resaon why the directory is removed, please?

**Comment by devxoul** [comment]
Why do you need `--no-use-binaries`?

**Comment by YukiOya** [comment]
We use the option for binary compatibility and debug using step execution.

>  I removed xcodeproj file to manage the library with only Swift Package Manager.

I understand. Thank you for your answering.
