### ISSUE TITLE
Release 2.0.0 Carthage issue

### ISSUE THREAD

**Issue by hongxinhope** [devxoul/URLNavigator#77]
Hello,
      A problem occurs in release 2.0.0 when using Carthage: 
      After ```Carthage update```, I can not find ```URLNavigator.framework``` file in ```Carthage/Build/...``` directory.
      However, release 1.3.0 is OK.

**Comment by devxoul** [comment]
Hmm yeah, it seems that Travis deployment was failed. I manually uploaded the binary. Please try again :)

**Comment by hongxinhope** [comment]
@devxoul 
Great! I think that's OK with the uploaded binary.

Actually, I found another error when Carthage updating:
```
*** Downloading URLNavigator.framework binary at "2.0.0"
*** Skipped installing URLNavigator.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.0 (swiftlang-900.0.65.2 clang-900.0.37) and the local version is 4.0 (swiftlang-900.0.65 clang-900.0.37)."
```

My local Xcode version is 9.0(9A235), not the latest, maybe it's the reason of this error.

**Comment by devxoul** [comment]
Maybe. Could you please update Xcode version to latest?

**Comment by hongxinhope** [comment]
@devxoul 

Unfortunately, same error with the latest Xcode Version 9.0.1 (9A1004)

```
*** Downloading URLNavigator.framework binary at "2.0.0"
*** Skipped installing URLNavigator.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.0 (swiftlang-900.0.65 clang-900.0.37) and the local version is 4.0 (swiftlang-900.0.65.2 clang-900.0.37)."
```

**Comment by devxoul** [comment]
@hongxinhope Hmm, could you please try again?

**Comment by hongxinhope** [comment]
@devxoul The updated binary is OK. Thank you very much! :-D
