### ISSUE TITLE
error when install by carthage

### ISSUE THREAD

**Issue by GarenChen** [devxoul/URLNavigator#78]
Hello,
A problem occurs in release 2.0.0 when using Carthage, it will install success,but error when compiles:

Module file's minimum deployment target is ios11.0 v11.0: /Users/.../Carthage/Build/iOS/URLNavigator.framework/Modules/URLNavigator.swiftmodule/x86_64.swiftmodule

but when I use 1.3.0 , carthage install fail， error:
"Incompatible Swift version - framework was built with 4.0 (swiftlang-900.0.65 clang-900.0.37) and the local version is 4.0 (swiftlang-900.0.65.2 clang-900.0.37)."

My local Xcode version is 9.0.1 (9A1004), could you help me

**Comment by devxoul** [comment]
@GarenChen, there was a small problem on prebuilt binary. Could you please try again?

**Comment by GarenChen** [comment]
it is OK when i install by Cocoapods

**Comment by qiushuitian** [comment]
My error  is below:

*** Skipped installing URLNavigator.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.0 (swiftlang-900.0.65 clang-900.0.37) and the local version is 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)."

**Comment by tdharmon** [comment]
@qiushuitian were you able to find a way around this issue? I'm also experiencing this issue (same version numbers as yours, too).

**Comment by devxoul** [comment]
@qiushuitian @tdharmon Apologize for the delay. I updated the prebuilt binary of [2.0.4](https://github.com/devxoul/URLNavigator/releases/tag/2.0.4). Please try again :pray:

**Comment by tdharmon** [comment]
@devxoul thank you!
