### ISSUE TITLE
Error in Release note 2.0.0 (Must remove Context object)

### ISSUE THREAD

**Issue by BabyAzerty** [devxoul/URLNavigator#80]
There is a release note error for v2

In the code example for 

> Mapping view controllers: Use register() to map view controllers. It takes a view controller factory instead of URLNavigable so that you can inject dependency to the view controller or create a view controller from Storyboard. Also, URLNavigable is removed.

The object `Context?` should be replaced by `Any?` in the `navigator.register` function

**Comment by devxoul** [comment]
@BabyAzerty, oh thanks! I just fixed it.
