### ISSUE TITLE
UIApplication.shared is not supported under app extension.

### ISSUE THREAD

**Issue by xieweizhi** [devxoul/URLNavigator#81]
UIApplication.shared  `'shared' is unavailable: Use view controller based solutions where appropriate instead.`

Here is a solution for your reference. https://miqu.me/blog/2016/11/28/app-extensions-xcode-and-cocoapods-omg/

**Comment by devxoul** [comment]
@xieweizhi, #82 is a patch for this issue. Could you please review that? Thanks for reporting!

**Comment by xieweizhi** [comment]
@devxoul 
 Yes, it's fixed in #82 :)
