### ISSUE TITLE
Crashed

### ISSUE THREAD

**Issue by butcheryl** [devxoul/URLNavigator#83]
iOS 11，iPhone 8 Plus 

1. create project

2. Main.storyboard
![image](https://user-images.githubusercontent.com/7799928/32480633-bdd241fc-c3ca-11e7-86f1-cf039054e292.jpeg)

3.  button clicked
```swift
@IBAction func push(sender: UIButton) {
    let vc = UIViewController()
    navigator.push(vc)
}
```

The third time clicked button，100% crashed！！！

2.0.1 has this issue，2.0.0 no

**Comment by devxoul** [comment]
Thanks for reporting. This is fixed in [2.0.2](https://github.com/devxoul/URLNavigator/releases/tag/2.0.2) :)
