### ISSUE TITLE
Carthage cannot build

### ISSUE THREAD

**Issue by kgonyon** [devxoul/URLNavigator#84]
```
*** Downloading URLNavigator.framework binary at "2.0.2"
*** Skipped installing URLNavigator.framework binary due to the error:
        "Incompatible Swift version - framework was built with 4.0 (swiftlang-900.0.65 clang-900.0.37) and the local version is 4.0.2 (swiftlang-900.0.69.2 clang-900.0.38)."
*** Checking out URLNavigator at "2.0.2"
*** xcodebuild output can be found in /var/folders/vz/3fwzpk4n73sd5qmp95675c600000gp/T/carthage-xcodebuild.CaYb0E.log
*** Skipped building URLNavigator due to the error:
Dependency "URLNavigator" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/devxoul/URLNavigator/issues/new
```
If you provide a shared scheme to build then Carthage will build a new binary with our version of swift. This will allow us to get around swift's version issues since it doesn't have a stable ABI.

**Comment by devxoul** [comment]
I just updated the prebuilt binary of 2.0.2 😃

**Comment by aehlke** [comment]
@devxoul Thanks! It's still failing with `Dependency "URLNavigator" has no shared framework schemes for any of the platforms: iOS` when using the `--no-use-binaries` option (necessary when building with a version of Xcode you didn't provide a prebuilt binary for, i.e. the Xcode beta).

**Comment by devxoul** [comment]
@aehlke, URLNavigator supports only prebuilt binaries for Carthage.
