### ISSUE TITLE
Can't transition to the newest version of URLNavigator

### ISSUE THREAD

**Issue by agisilaos** [devxoul/URLNavigator#88]
Hello @devxoul. First of all thanks for making this Navigator it's so helpful. I have a hard time to transition to the new version of the Navigator because of some issues. I know that .map has been deprecated but I have a hard time to find with what to replace it. Here's the errors that I keep getting:

If I can understand what I need to change etc I would be more than happy to make a migrate doc with more explanation in the docs about how and why things need to change for the 2nd version.

Thanks for the help in advance @devxoul! 

![33952674-3b87e44e-e03b-11e7-8cd8-7b606e049c12](https://user-images.githubusercontent.com/10944108/43145777-81350508-8f68-11e8-8c22-f605fd9da94b.png)
<img width="723" alt="screen shot 2017-12-13 at 19 13 02" src="https://user-images.githubusercontent.com/10944108/33952675-3bb0e092-e03b-11e7-8c89-d281b3654edd.png">
<img width="718" alt="screen shot 2017-12-13 at 19 13 16" src="https://user-images.githubusercontent.com/10944108/33952677-3cfd7f6e-e03b-11e7-8ad0-ed2be7ccc565.png">

**Comment by devxoul** [comment]
@agisilaos, you can check the migration guide https://github.com/devxoul/URLNavigator/releases/tag/2.0.0 :)

**Comment by agisilaos** [comment]
Hello @devxoul, I'm back at the migrating to the newest version of URLNavigator. I managed to fix all issues except the one related to `.map`. I tried to read through the guides and try to migrate the code myself but couldn't find a solution. 

How and what you believe is the correct way to update my code to support  URL Navigator `2.0.6`, so I can achieve the same functionality?

Thank you in advance for all the help.

![screenshot](https://user-images.githubusercontent.com/10944108/43145777-81350508-8f68-11e8-8c22-f605fd9da94b.png)

**Comment by agisilaos** [comment]
Hm after some more digging I think I found a possible solution but I'm not sure if that's the correct one so I would love your input. 

```swift
struct NavigationMap {

    static func initialize() {
        navigator.handle("URL of my link") { url, values, context in
            return true
        }
    }
}
```

**Comment by agisilaos** [comment]
Thank you @devxoul!
