### ISSUE TITLE
Can't Ingegration with carthage of the swift4.0.3 version.

### ISSUE THREAD

**Issue by qiushuitian** [devxoul/URLNavigator#89]
I integration  with carthage.
The cart Cartfile is below:

    github "devxoul/URLNavigator"

And run:

    carthage update --platform ios

It has error below:

    *** Skipped installing URLNavigator.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.0 (swiftlang-900.0.65 clang-900.0.37) and the local version is 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)."

And I download the newest release framework, it has the same tips.

**Comment by devxoul** [comment]
I updated the prebuilt binary. Could you please try again?

**Comment by qiushuitian** [comment]
Yes, it works! thank you very much
